# Generated by Django 5.2.17 on 2026-09-06 06:32

from django.contrib.auth import get_user_model
from django.db import migrations


def create_owner_profiles(apps, schema_editor):
    """
    Every user that existed before roles were introduced was, by definition,
    running the whole show — give them all the Owner role so nobody who
    could previously do everything suddenly gets locked out.
    """
    UserProfile = apps.get_model('restaurants', 'UserProfile')
    User = apps.get_model(get_user_model()._meta.app_label, get_user_model()._meta.model_name)
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user, defaults={'role': 'owner'})


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_owner_profiles, noop_reverse),
    ]
