# Generated by Django 5.2.17 on 2026-09-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurant_plan_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_reports',
            field=models.BooleanField(default=False, help_text='Sales summary, top-selling items, and stock reports (the Reports screen).'),
        ),
    ]
