# Generated by Django 5.2.17 on 2026-09-22 18:42

from django.db import migrations, models


def enable_for_premium(apps, schema_editor):
    Plan = apps.get_model('restaurants', 'Plan')
    Plan.objects.filter(name__iexact='Premium').update(has_manage_users=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_plan_has_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_manage_users',
            field=models.BooleanField(default=False, help_text='Adding/editing staff accounts and roles (the Manage Users screen).'),
        ),
        migrations.RunPython(enable_for_premium, noop),
    ]
