# Generated by Django 5.2.17 on 2026-09-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_plan_has_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_kitchen',
            field=models.BooleanField(default=False, help_text='Kitchen order queue screen (web and mobile). Off by default — a retail/mart tenant has no use for it; a restaurant tenant buys it as a premium feature.'),
        ),
    ]
