# Generated by Django 5.2.17 on 2026-09-06 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0003_order_client_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariant',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='track_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Positive for stock in, negative for stock out.')),
                ('resulting_quantity', models.IntegerField(help_text='stock_quantity snapshot immediately after this movement.')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_line', models.ForeignKey(blank=True, help_text='Set when movement_type is "sale" — links back to the order line that caused it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.orderline')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='menu.itemvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
