# Generated by Django 5.2.17 on 2026-09-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_table_number_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
